#!/bin/sh

# Copyright (c) 2019 Andrew Steel <copyright@andrewsteel.net>
#
# SPDX-License-Identifier: MIT-0
#
# The MIT No Attribution License:
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# otpclient-decrypt:
# Decrypts the OTPClient encrypted database.
# Currently only decrypts the andOTP password-encrypted backup of the database.
# Requires `andotp-decrypt` from my `misc-python` repository.

FILE_BACKUP_ANDOTP="${HOME}/.var/app/com.github.paolostivanin.OTPClient/data/andotp_exports.json.aes"

unset -v \
	deps_missing
for COMMAND in \
	python \
	andotp-decrypt
do
	if ! test "$(command -v "${COMMAND}")"; then
		printf '%s: %s\n' \
			"$(basename "${0}")" \
			"\`${COMMAND}\` not found in PATH" \
			>&2
		deps_missing=1
	fi
done
test "${deps_missing}" && exit 1

andotp-decrypt "${FILE_BACKUP_ANDOTP}" \
| python -m json.tool
