#!/bin/sh

# Copyright (c) 2019 Andrew Steel <copyright@andrewsteel.net>
#
# SPDX-License-Identifier: MIT-0
#
# The MIT No Attribution License:
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# steam-shortcuts-bingen:
# Generates executables for installed Steam shortcuts.
#
# Executables for each shortcut, accepting '--print-appid' and '--print-target'
# parameters, should be present in "${HOME}/.local/lib/steam/shortcut".
# Additionally, STEAMROOT and STEAMID3 environment variables must be defined.

CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}/steam-shortcuts/bin"
mkdir -p "${CACHE_HOME}"
rm -f "${CACHE_HOME}/"*

cd "${HOME}/.local/lib/steam/shortcut"
IFS="$(printf '\n!')"; IFS="${IFS%!}"
for SHORTCUT in $(ls .); do
	< "${STEAMROOT}/userdata/${STEAMID3}/config/shortcuts.vdf" \
	grep -q "$(./"${SHORTCUT}" --print-target)" \
	&& {
		BINFILE="${CACHE_HOME}/steam-shortcut.${SHORTCUT}"
		printf '%s\n' \
			'#!/bin/sh' \
			'' \
			"steam steam://rungameid/$(./"${SHORTCUT}" --print-appid)" \
		> "${BINFILE}"
		chmod +x "${BINFILE}"
	}
done
