#!/bin/sh

IFS="$(printf ' \t\n!')"; IFS="${IFS%!}"

unset -v \
	switch_count
while test "${#}" -gt '0'; do
	case "${1}" in
		( '-c' \
		| '--c' \
		| '--co' \
		| '--cou' \
		| '--coun' \
		| '--count' )
			switch_count='TRUE'
			;;
		( '--h' \
		| '--he' \
		| '--hel' \
		| '--help' )
			printf '%s:\n' 'Usage'
			printf '  %s [%s]...\n' \
				"$(basename "${0}")" \
				'OPTION'
			echo
			printf '%s\n' \
				'Searches the Steam install directory for shell scripts and finds potential' \
				'environment variables defined within.'
			echo
			printf '%s:\n' 'Options'
			printf '%5s %-11s %s\n' \
				'-c,' \
				'--count' \
				'display and sort by descending occurrence counts' \
				'' \
				'--help' \
				'print this and exit'
			exit
			;;
		(*)
			printf '%s: %s\n' \
				"$(basename "${0}")" \
				'unrecognized option '\'"${1}"\' \
				>&2
			echo >&2
			"${0}" --help >&2
			exit
			;;
	esac
	shift
done
PARAM_COUNT="${switch_count}"

(
	IFS="$(printf '\n!')"; IFS="${IFS%!}"

	cat $(
		find "${STEAMROOT:-${XDG_DATA_HOME:-${HOME}/.local/share}/Steam}" \
			-type f \
		| grep -F '.sh'
	) \
	| sed -n 's/.*\(STEAM[_A-Z]*\).*/\1/p' \
	| LC_ALL=C sort \
	| (
		if test "${PARAM_COUNT}"; then
			uniq -c \
			| sort -nr
		else
			uniq
		fi
	)
)

