#!/bin/sh

# Copyright (c) 2019 Andrew Steel <copyright@andrewsteel.net>
#
# SPDX-License-Identifier: MIT-0
#
# The MIT No Attribution License:
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# code:
# Launches "Visual Studio Code".

# Which trash provider to use.
#   * gio: GNOME
export ELECTRON_TRASH='gio'

# Disable NPM update notifier.
# Fixes startup delay for ESLint extension.
export NO_UPDATE_NOTIFIER='1'

# Force dark GTK theme if GTK_THEME not set.
export GTK_THEME="${GTK_THEME:-$(
	GTK_THEME_CURRENT="$(
		gsettings get \
			org.gnome.desktop.interface gtk-theme \
			2> /dev/null
	)"
	if test "${GTK_THEME_CURRENT}"; then
		printf '%s' "${GTK_THEME_CURRENT}:dark"
	fi
)}"

# Launch Visual Studio Code with forced hardware acceleration.
exec "$(command -pv code)" --ignore-gpu-blacklist "${@}"

